POST http://localhost:5079/categories/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM3YmZjZDJhLTgzZDktNDE3ZC05OGQwLWQ0YjlhODVkZDE2YSIsIm5iZiI6MTY5NTkxNTMzNiwiZXhwIjoxNjk2NTIwMTM2LCJpYXQiOjE2OTU5MTUzMzZ9.xKfS11Mc7ztYGBD-U8ColnyJVqWlVjM18GQuOeHAFPc
Content-Type: application/json

{
  "name": "SexToys",
  "description": "well the speaks for itself",
  "Slug": "sex"
}